<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Sharpener.Rest</PackageId>
    <Description>Quality of life tools for C# with respect to http and rest requests.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>quality-of-life qol dotnet csharp http rest</PackageTags>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <PackageVersion>1.0.1</PackageVersion>
    <AssemblyVersion>$(SharedPackageVersion)</AssemblyVersion>
    <FileVersion>$(SharedPackageVersion)</FileVersion>
    <InformationalVersion>$(SharedPackageVersion)+$(GitCommitId)</InformationalVersion>
    <Version>$(SharedPackageVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Link>Docs\README.md</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sharpener.Json\Sharpener.Json.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http"/>
    <PackageReference Include="Microsoft.Extensions.Http"/>
  </ItemGroup>
</Project>
