<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Sharpener.NamedResources</PackageId>
    <Description>Enum driven population of strongly typed named resources and their corresponding constants.</Description>
    <PackageReadmeFile>NAMED_RESOURCES.md</PackageReadmeFile>
    <PackageTags>quality-of-life enum strong typing dotnet csharp</PackageTags>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\docs\NAMED_RESOURCES.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Link>Docs\README.md</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Docs\"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\gen\Sharpener.NamedResources.Generators\Sharpener.NamedResources.Generators.csproj" 
    ReferenceOutputAssembly="false"
    PrivateAssets="all"/>
    <ProjectReference Include="..\Sharpener\Sharpener.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <!-- Pack the generator dll as an analyzer -->
    <None Include="..\..\gen\Sharpener.NamedResources.Generators\bin\$(Configuration)\netstandard2.0\Sharpener.NamedResources.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false"/>
  </ItemGroup>
</Project>
