<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Sharpener.NamedResources</PackageId>
    <Description>Enum driven population of strongly typed named resources and their corresponding constants.</Description>
    <PackageReadmeFile>JSON.md</PackageReadmeFile>
    <PackageTags>quality-of-life enum strong typing dotnet csharp</PackageTags>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\docs\NAMED_RESOURCES.md">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Link>Docs\README.md</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Docs\"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\gen\Sharpener.NamedResources.Generators\Sharpener.NamedResources.Generators.csproj" />
    <ProjectReference Include="..\Sharpener\Sharpener.csproj"/>
  </ItemGroup>
</Project>
