name: Build and Deploy NuGet Package
on:
  push:
    paths:
     - '.github/workflows/**'
     - 'src/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
     - '.github/workflows/**'
     - 'src/**'
    types: [closed]
    branches:
        - main
        - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Update NuGet Package
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore --source "https://api.nuget.org/v3/index.json" --no-cache
        if ! nuget sources list | grep -q "nuget.org"; then
          nuget sources add -name "nuget.org" -source "https://api.nuget.org/v3/index.json" -username ${{ secrets.NUGET_PUBLISH_USERNAME }} -password ${{ secrets.NUGET_PUBLISH_API_KEY }}
        fi
      shell: bash
    - name: Build and package
      run: |
        dotnet build --configuration Release --no-restore --source https://api.nuget.org/v3/index.json --verbosity minimal
        if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          dotnet pack --configuration Release --no-restore --no-build --output ./bin/Release --version-suffix "alpha-${{ github.sha }}"
        else
          dotnet pack --configuration Release --no-restore --no-build --output ./bin/Release
        fi
    - name: Publish package to nuget.org
      run: |
        for PACKAGE in $(ls ./bin/Release/*.nupkg); do
          dotnet nuget push $PACKAGE -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_PUBLISH_API_KEY }} --skip-duplicate
        done
