name: Build and Deploy NuGet Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
        - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Update NuGet Package
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Determine changed projects
      run: |
        CHANGED_FILES=$(git --no-pager diff --name-only HEAD $(git merge-base HEAD ${{ github.base_ref }}) | grep ".csproj")
        PROJECTS=$(echo $CHANGED_FILES | sed "s/ /;/g")
        echo "::set-env name=PROJECTS::$PROJECTS"
    - name: Build and package
      run: |
        dotnet build --configuration Release --no-restore --source https://api.nuget.org/v3/index.json --verbosity minimal --projects ${{ env.PROJECTS }}
        dotnet pack --configuration Release --no-restore --no-build --output ./bin/Release ${{ env.PROJECTS }}
    - name: Authenticate with nuget.org
      run: nuget sources add -name "nuget.org" -source "https://api.nuget.org/v3/index.json" -username ${{ secrets.NUGET_PUBLISH_USERNAME }} -password ${{ secrets.NUGET_PUBLISH_API_KEY }}
    - name: Publish package to nuget.org
      run: |
        for PACKAGE in $(ls ./bin/Release/*.nupkg); do
          dotnet nuget push $PACKAGE -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_PUBLISH_API_KEY }}
        done
